name: GitHub Streak Stats

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch: # Allows you to run it manually

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Streak Stats
        uses: DenverCoder1/github-readme-streak-stats-action@v1.0.0
        with:
          gh_token: ${{ secrets.GH_TOKEN }}
          user: itsdakshjain
          theme: dark

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add streak-stats.svg
          git commit -m "Update streak stats" || exit 0
          git push
